// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: proto/policy/policy.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPv4PrefixPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed prefixes for the group.
	AllowedPrefixes []string `protobuf:"bytes,1,rep,name=allowed_prefixes,json=allowedPrefixes,proto3" json:"allowed_prefixes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IPv4PrefixPolicy) Reset() {
	*x = IPv4PrefixPolicy{}
	mi := &file_proto_policy_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv4PrefixPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv4PrefixPolicy) ProtoMessage() {}

func (x *IPv4PrefixPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv4PrefixPolicy.ProtoReflect.Descriptor instead.
func (*IPv4PrefixPolicy) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{0}
}

func (x *IPv4PrefixPolicy) GetAllowedPrefixes() []string {
	if x != nil {
		return x.AllowedPrefixes
	}
	return nil
}

type GroupPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Constraint for IPv4 prefixes.
	Ipv4Policy    *IPv4PrefixPolicy `protobuf:"bytes,1,opt,name=ipv4_policy,json=ipv4Policy,proto3" json:"ipv4_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPolicy) Reset() {
	*x = GroupPolicy{}
	mi := &file_proto_policy_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPolicy) ProtoMessage() {}

func (x *GroupPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPolicy.ProtoReflect.Descriptor instead.
func (*GroupPolicy) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{1}
}

func (x *GroupPolicy) GetIpv4Policy() *IPv4PrefixPolicy {
	if x != nil {
		return x.Ipv4Policy
	}
	return nil
}

var File_proto_policy_policy_proto protoreflect.FileDescriptor

const file_proto_policy_policy_proto_rawDesc = "" +
	"\n" +
	"\x19proto/policy/policy.proto\x12\fgribi.policy\"=\n" +
	"\x10IPv4PrefixPolicy\x12)\n" +
	"\x10allowed_prefixes\x18\x01 \x03(\tR\x0fallowedPrefixes\"N\n" +
	"\vGroupPolicy\x12?\n" +
	"\vipv4_policy\x18\x01 \x01(\v2\x1e.gribi.policy.IPv4PrefixPolicyR\n" +
	"ipv4PolicyB,Z*github.com/openconfig/gribigo/proto/policyb\x06proto3"

var (
	file_proto_policy_policy_proto_rawDescOnce sync.Once
	file_proto_policy_policy_proto_rawDescData []byte
)

func file_proto_policy_policy_proto_rawDescGZIP() []byte {
	file_proto_policy_policy_proto_rawDescOnce.Do(func() {
		file_proto_policy_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_policy_policy_proto_rawDesc), len(file_proto_policy_policy_proto_rawDesc)))
	})
	return file_proto_policy_policy_proto_rawDescData
}

var file_proto_policy_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_policy_policy_proto_goTypes = []any{
	(*IPv4PrefixPolicy)(nil), // 0: gribi.policy.IPv4PrefixPolicy
	(*GroupPolicy)(nil),      // 1: gribi.policy.GroupPolicy
}
var file_proto_policy_policy_proto_depIdxs = []int32{
	0, // 0: gribi.policy.GroupPolicy.ipv4_policy:type_name -> gribi.policy.IPv4PrefixPolicy
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_policy_policy_proto_init() }
func file_proto_policy_policy_proto_init() {
	if File_proto_policy_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_policy_policy_proto_rawDesc), len(file_proto_policy_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_policy_policy_proto_goTypes,
		DependencyIndexes: file_proto_policy_policy_proto_depIdxs,
		MessageInfos:      file_proto_policy_policy_proto_msgTypes,
	}.Build()
	File_proto_policy_policy_proto = out.File
	file_proto_policy_policy_proto_goTypes = nil
	file_proto_policy_policy_proto_depIdxs = nil
}
